version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/app
    ports:
      - "3000:3000"
