FROM python:3.10

# Define variáveis de ambiente
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Copia o código fonte do backend
COPY ./ .

# Instalação das dependências do backend
RUN pip install Django==5.0.4
RUN pip install -r requirements.txt

# Expose a porta 8000 para o servidor web do backend
EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
