FROM python:3.10

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY ./ ./

RUN pip install Django==5.0.4
RUN pip install gunicorn
RUN pip install -r requirements.txt

# Executa as migrações do Django
RUN python manage.py migrate
RUN python manage.py makemigrations


EXPOSE 8000

# Comando para iniciar o aplicativo usando Gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "setup.wsgi"]